resolver: lts-12.11
packages:
- cursor
- cursor-gen
extra-deps:
- genvalidity-0.6.1.0
- genvalidity-containers-0.5.1.0
- genvalidity-text-0.5.1.0
- genvalidity-aeson-0.2.0.2
- genvalidity-property-0.2.1.1
- genvalidity-hspec-0.6.2.0
- genvalidity-hspec-optics-0.1.1.0
- validity-0.8.0.0
- validity-containers-0.3.1.0
- validity-text-0.3.1.0
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/886871538c15681575925a990a3f1b68ed9d5477.tar.gz" ]
