name: cursor-gen
version: '0.3.0.0'
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2018 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/cursor
category: Cursor
synopsis: Generators for Purely Functional Cursors
description: Generators for Purely Functional Cursors for common data structures
extra-source-files:
- CHANGELOG.md

dependencies:
- base <5

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck 
  - containers
  - cursor >=0.2
  - genvalidity >=0.8
  - genvalidity-containers
  - genvalidity-text
  - genvalidity-text >=0.6
  - text

tests:
  cursor-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - containers
    - cursor
    - cursor-gen
    - genvalidity-hspec
    - genvalidity-hspec-optics
    - hspec
    - microlens
    - pretty-show
    - text

benchmarks:
  cursor-bench:
    main: Bench.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - criterion
    - cursor
    - cursor-gen
    - genvalidity-criterion
