name: cursor-gen
version: '0.0.0.0'
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2018 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/cursor
category: Cursor
synopsis: Generators for Purely Functional Cursors
description: Generators for Purely Functional Cursors for common data structures


library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck 
  - base <5
  - containers
  - cursor 
  - genvalidity
  - genvalidity-containers
  - genvalidity-text
  - text

tests:
  cursor-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - base
    - containers
    - cursor
    - cursor-gen
    - genvalidity-hspec
    - genvalidity-hspec-optics
    - hspec
    - microlens
    - pretty-show
    - text
